name: totask
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: null
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: null
  firebase_auth: null
  firebase_core: null
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_quill: null
  get: 4.3.4
  google_fonts: ^2.1.0
  google_sign_in: null
  intl: null
  line_icons: null
  lottie: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
